
var articles = [
  {
    'ref':'pr',
    'nom':'Poivrons rouges',
    'catégorie' : 'Légumes',
    'photos':[
      {
        'url':'fruits_legumes_1.jpg',
        'type':'sprite',
        'x': 15,
        'y':16,
        'w':163,
        'h':112,
      },
    ],
  },
  {
    'ref':'be',
    'nom':'Betteraves',
    'catégorie' : 'Légumes',
    'photos':[
      {
        'url':'fruits_legumes_1.jpg',
        'type':'sprite',
        'x': 204,
        'y':10,
        'w':155,
        'h':130,
      },
      {
        'url':'fruits_legumes_2.jpg',
        'type':'sprite',
        'x':608,
        'y':428,
        'w':183,
        'h':118,
      },
    ],
  },
  {
    'ref':'or',
    'nom':'Oranges',
    'catégorie' : 'Fruits',
    'photos':[
      {
        'url':'fruits_legumes_1.jpg',
        'type':'sprite',
        'x': 375,
        'y':25,
        'w':130,
        'h':116,
      },
      {
        'url':'fruits_legumes_2.jpg',
        'type':'sprite',
        'x': 14,
        'y':427,
        'w':202,
        'h':132,
      },
    ],
  },
  {
    'ref':'sa',
    'nom':'Salades',
    'catégorie' : 'Légumes',
    'photos':[
      {
        'url':'fruits_legumes_1.jpg',
        'type':'sprite',
        'x': 507,
        'y':18,
        'w':179,
        'h':140,
      },
    ],
  },
  {
    'ref':'an',
    'nom':'Ananas',
    'catégorie' : 'Fruits',
    'photos':[
      {
        'url':'fruits_legumes_1.jpg',
        'type':'sprite',
        'x': 690,
        'y':7,
        'w':84,
        'h':189,
      },
    ],
  },
  {
    'ref':'cv',
    'nom':'Citrons Verts',
    'catégorie' : 'Fruits',
    'photos':[
      {
        'url':'fruits_legumes_1.jpg',
        'type':'sprite',
        'x': 11,
        'y':127,
        'w':144,
        'h':140,
      },
    ],
  },
  {
    'ref':'ca',
    'nom':'Carottes',
    'catégorie' : 'Légumes',
    'photos':[
      {
        'url':'fruits_legumes_1.jpg',
        'type':'sprite',
        'x': 155,
        'y':127,
        'w':183,
        'h':131,
      },
      {
        'url':'fruits_legumes_2.jpg',
        'type':'sprite',
        'x':595,
        'y':152,
        'w':206,
        'h':118,
      },
    ],
  },
  {
    'ref':'ps',
    'nom':'Pastèques',
    'catégorie' : 'Fruits',
    'photos':[
      {
        'url':'fruits_legumes_1.jpg',
        'type':'sprite',
        'x': 329,
        'y':144,
        'w':147,
        'h':129,
      },
    ],
  },
  {
    'ref':'pa',
    'nom':'Pamplemousses',
    'catégorie' : 'Fruits',
    'photos':[
      {
        'url':'fruits_legumes_2.jpg',
        'type':'sprite',
        'x':208,
        'y':4,
        'w':189,
        'h':144,
      },
      {
        'url':'fruits_legumes_1.jpg',
        'type':'sprite',
        'x': 489,
        'y':147,
        'w':120,
        'h':127,
      },
      {
        'url':'fruits_legumes_1.jpg',
        'type':'sprite',
        'x':349,
        'y':511,
        'w':132,
        'h':128,
      },
    ],
  },
  {
    'ref':'ki',
    'nom':'Kiwis',
    'catégorie' : 'Fruits',
    'photos':[
      {
        'url':'fruits_legumes_1.jpg',
        'type':'sprite',
        'x': 606,
        'y':182,
        'w':162,
        'h':96,
      },
      {
        'url':'fruits_legumes_2.jpg',
        'type':'sprite',
        'x':192,
        'y':154,
        'w':206,
        'h':118,
      },
    ],
  },
  {
    'ref':'ra',
    'nom':'Raisins',
    'catégorie' : 'Fruits',
    'photos':[
      {
        'url':'fruits_legumes_1.jpg',
        'type':'sprite',
        'x': 10,
        'y':268,
        'w':161,
        'h':109,
      },
    ],
  },
  {
    'ref':'poi',
    'nom':'Poires',
    'catégorie' : 'Fruits',
    'photos':[
      {
        'url':'fruits_legumes_1.jpg',
        'type':'sprite',
        'x':162,
        'y':268,
        'w':161,
        'h':109,
      },
      {
        'url':'fruits_legumes_2.jpg',
        'type':'sprite',
        'x':397,
        'y':288,
        'w':206,
        'h':118,
      },
    ],
  },
  {
    'ref':'pi',
    'nom':'Piments',
    'catégorie' : 'Légumes',
    'photos':[
      {
        'url':'fruits_legumes_1.jpg',
        'type':'sprite',
        'x': 326,
        'y':269,
        'w':175,
        'h':107,
      },
      {
        'url':'fruits_legumes_2.jpg',
        'type':'sprite',
        'x': 5,
        'y':17,
        'w':206,
        'h':111,
      },
    ],
  },
  {
    'ref':'pe',
    'nom':'Pêches',
    'catégorie' : 'Fruits',
    'photos':[
      {
        'url':'fruits_legumes_1.jpg',
        'type':'sprite',
        'x': 500,
        'y':275,
        'w':116,
        'h':109,
      },
    ],
  },
  {
    'ref':'co',
    'nom':'Concombres',
    'catégorie' : 'Légumes',
    'photos':[
      {
        'url':'fruits_legumes_1.jpg',
        'type':'sprite',
        'x': 616,
        'y':277,
        'w':171,
        'h':109,
      },
      {
        'url':'fruits_legumes_2.jpg',
        'type':'sprite',
        'x': 9,
        'y':294,
        'w':206,
        'h':118,
      },
    ],
  },
  {
    'ref':'ci',
    'nom':'Citrons',
    'catégorie' : 'Fruits',
    'photos':[
      {
        'url':'fruits_legumes_1.jpg',
        'type':'sprite',
        'x':38,
        'y':383,
        'w':123,
        'h':109,
      },
      {
        'url':'fruits_legumes_2.jpg',
        'type':'sprite',
        'x':220,
        'y':292,
        'w':183,
        'h':118,
      },
    ],
  },
  {
    'ref':'pm',
    'nom':'Pommes',
    'catégorie' : 'Légumes',
    'photos':[
      {
        'url':'fruits_legumes_1.jpg',
        'type':'sprite',
        'x':181,
        'y':383,
        'w':106,
        'h':109,
      },
      {
        'url':'fruits_legumes_2.jpg',
        'type':'sprite',
        'x':595,
        'y':289,
        'w':206,
        'h':118,
      },
    ],
  },
  {
    'ref':'cf',
    'nom':'Choux-Fleur',
    'catégorie' : 'Légumes',
    'photos':[
      {
        'url':'fruits_legumes_1.jpg',
        'type':'sprite',
        'x':303,
        'y':391,
        'w':115,
        'h':109,
      },
    ],
  },
  {
    'ref':'ba',
    'nom':'Bananes',
    'catégorie' : 'Fruits',
    'photos':[
      {
        'url':'fruits_legumes_1.jpg',
        'type':'sprite',
        'x': 445,
        'y':399,
        'w':145,
        'h':100,
      },
    ],
  },
  {
    'ref':'au',
    'nom':'Aubergines',
    'catégorie' : 'Légumes',
    'photos':[
      {
        'url':'fruits_legumes_1.jpg',
        'type':'sprite',
        'x':620,
        'y':407,
        'w':170,
        'h':100,
      },
    ],
  },
  {
    'ref':'bo',
    'nom':'Brocolis',
    'catégorie' : 'Légumes',
    'photos':[
      {
        'url':'fruits_legumes_1.jpg',
        'type':'sprite',
        'x':11,
        'y':508,
        'w':170,
        'h':127,
      },
    ],
  },
  {
    'ref':'nc',
    'nom':'Noix de Coco',
    'catégorie' : 'Fruits',
    'photos':[
      {
        'url':'fruits_legumes_1.jpg',
        'type':'sprite',
        'x':184,
        'y':515,
        'w':156,
        'h':119,
      },
      {
        'url':'fruits_legumes_2.jpg',
        'type':'sprite',
        'x':222,
        'y':428,
        'w':206,
        'h':118,
      },
    ],
  },
  {
    'ref':'av',
    'nom':'Avocats',
    'catégorie' : 'Légumes',
    'photos':[
      {
        'url':'fruits_legumes_1.jpg',
        'type':'sprite',
        'x':484,
        'y':514,
        'w':143,
        'h':124,
      },
      {
        'url':'fruits_legumes_2.jpg',
        'type':'sprite',
        'x': 403,
        'y':22,
        'w':189,
        'h':111,
      },
    ],
  },
  {
    'ref':'to',
    'nom':'Tomates',
    'catégorie' : 'Fruits',
    'photos':[
      {
        'url':'fruits_legumes_1.jpg',
        'type':'sprite',
        'x':641,
        'y':513,
        'w':136,
        'h':119,
      },
      {
        'url':'fruits_legumes_2.jpg',
        'type':'sprite',
        'x':391,
        'y':154,
        'w':206,
        'h':118,
      },
    ],
  },
  {
    'ref':'fr',
    'nom':'Fraises',
    'catégorie' : 'Fruits',
    'photos':[
      {
        'url':'fruits_legumes_2.jpg',
        'type':'sprite',
        'x':424,
        'y':420,
        'w':188,
        'h':140,
      },
      {
        'url':'fruits_legumes_1.jpg',
        'type':'sprite',
        'x':25,
        'y':639,
        'w':118,
        'h':135,
      },
    ],
  },
  {
    'ref':'br',
    'nom':'Bananes Rouges',
    'catégorie' : 'Fruits',
    'photos':[
      {
        'url':'fruits_legumes_1.jpg',
        'type':'sprite',
        'x':156,
        'y':645,
        'w':191,
        'h':119,
      },
      {
        'url':'fruits_legumes_2.jpg',
        'type':'sprite',
        'x':586,
        'y':26,
        'w':206,
        'h':111,
      },
    ],
  },
  {
    'ref':'ma',
    'nom':'Mangues',
    'catégorie' : 'Fruits',
    'photos':[
      {
        'url':'fruits_legumes_1.jpg',
        'type':'sprite',
        'x':346,
        'y':647,
        'w':141,
        'h':119,
      },
    ],
  },
  {
    'ref':'cl',
    'nom':'Clémentines',
    'catégorie' : 'Fruits',
    'photos':[
      {
        'url':'fruits_legumes_1.jpg',
        'type':'sprite',
        'x':496,
        'y':649,
        'w':155,
        'h':119,
      },
    ],
  },
  {
    'ref':'cx',
    'nom':'Choux',
    'catégorie' : 'Légumes',
    'photos':[
      {
        'url':'fruits_legumes_1.jpg',
        'type':'sprite',
        'x':657,
        'y':645,
        'w':120,
        'h':119,
      },
    ],
  },
  {
    'ref':'pj',
    'nom':'Poivrons jaunes',
    'catégorie' : 'Légumes',
    'photos':[
      {
        'url':'fruits_legumes_2.jpg',
        'type':'sprite',
        'x': 8,
        'y':141,
        'w':183,
        'h':146,
      },
    ],
  },
  {
    'ref':'po',
    'nom':'Poivrons oranges',
    'catégorie' : 'Légumes',
    'photos':[
      {
        'url':'fruits_legumes_2.jpg',
        'type':'sprite',
        'x': 8,
        'y':141,
        'w':183,
        'h':146,
      },
    ],
  },
]
