
var tarifs = [
  {
    'ref':'pr',
    'origine':'France',
    'prix':2.30,
    'unité':'Kg'
  },
  {
    'ref':'be',
    'origine':'France',
    'prix':1.10,
    'unité':'Botte'
  },
  {
    'ref':'or',
    'origine':'Espagne',
    'prix':1.5,
    'unité':'Kg'
  },
  {
    'ref':'sa',
    'origine':'France',
    'prix':0.50,
    'unité':'Pièce'
  },
  {
    'ref':'an',
    'origine':'Côte d\'Ivoire',
    'prix':1.79,
    'unité':'Pièce'
  },
  {
    'ref':'an',
    'origine':'Ghana',
    'prix':1.72,
    'unité':'Pièce'
  },
  {
    'ref':'cv',
    'origine':'Brésil',
    'prix':1.99,
    'unité':'Pièce'
  },
  {
    'ref':'ca',
    'origine':'France',
    'prix':0.9,
    'unité':'Botte'
  },
  {
    'ref':'ps',
    'origine':'Espagne',
    'prix':2.10,
    'unité':'Pièce'
  },
  {
    'ref':'pa',
    'origine':'Espagne',
    'prix':1.20,
    'unité':'Kg'
  },
  {
    'ref':'ki',
    'origine':'Nouvelle-Zélande',
    'prix':2.30,
    'unité':'Barquette 100g'
  },
  {
    'ref':'ra',
    'origine':'France',
    'prix':3.50,
    'unité':'Plateau 4Kg'
  },
  {
    'ref':'poi',
    'origine':'France',
    'prix':1.70,
    'unité':'Kg'
  },
  {
    'ref':'pi',
    'origine':'Mexique',
    'prix':0.82,
    'unité':'Kg'
  },
  {
    'ref':'pe',
    'origine':'France',
    'prix':1.13,
    'unité':'Kg'
  },
  {
    'ref':'co',
    'origine':'Brésil',
    'prix':1.46,
    'unité':'Pièce'
  },
  {
    'ref':'ci',
    'origine':'Espagne',
    'prix':0.51,
    'unité':'Pièce'
  },
  {
    'ref':'pm',
    'origine':'France',
    'prix':1.48,
    'unité':'Kg'
  },
  {
    'ref':'cf',
    'origine':'Belgique',
    'prix':2,
    'unité':'Kg'
  },
  {
    'ref':'ba',
    'origine':'Madagascar',
    'prix':1.20,
    'unité':'Kg'
  },
  {
    'ref':'ba',
    'origine':'Martinique',
    'prix':1.25,
    'unité':'Kg'
  },
  {
    'ref':'au',
    'origine':'Turquie',
    'prix':1.25,
    'unité':'Kg'
  },
  {
    'ref':'bo',
    'origine':'Espagne',
    'prix':1.20,
    'unité':'Pièce'
  },
  {
    'ref':'nc',
    'origine':'Côte d\'Ivoire',
    'prix':0.80,
    'unité':'Pièce'
  },
  {
    'ref':'av',
    'origine':'Pérou',
    'prix':1.09,
    'unité':'Pièce'
  },
  {
    'ref':'to',
    'origine':'France',
    'prix':1.20,
    'unité':'Plateau de 12'
  },
  {
    'ref':'to',
    'origine':'France',
    'prix':1.00,
    'unité':'Kg'
  },
  {
    'ref':'fr',
    'origine':'France',
    'prix':3,
    'unité':'Barquette 250g'
  },
  {
    'ref':'fr',
    'origine':'France',
    'prix':5,
    'unité':'Barquette 500g'
  },
  {
    'ref':'fr',
    'origine':'Espagne',
    'prix':8,
    'unité':'Plateau 1kg'
  },
  {
    'ref':'br',
    'origine':'Maroc',
    'prix':2,
    'unité':'Pièce'
  },
  {
    'ref':'ma',
    'origine':'Brésil',
    'prix':1.00,
    'unité':'Pièce'
  },
  {
    'ref':'cl',
    'origine':'Corse',
    'prix':2.15,
    'unité':'Plateeau 1Kg'
  },
  {
    'ref':'cx',
    'origine':'Belgique',
    'prix':1.12,
    'unité':'Pièce'
  },
  {
    'ref':'pj',
    'origine':'France',
    'prix':2.30,
    'unité':'Kg'
  },
  {
    'ref':'po',
    'origine':'France',
    'prix':2.30,
    'unité':'Kg'
  },
]
